name: prsk Doctor Deps

on:
  # 導入する場合は以下のコメントアウトを解除し、
  # スケジュール日時は必要に応じて調整してください。

  # schedule:
  #   # 毎週金曜日の25時
  #   - cron: "0 16 * * 5"
  workflow_dispatch:

jobs:
  doctor-deps:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: narumikr/link-sekai-actions/prsk-doctor-deps@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}