# .github/workflows/prsk-cheering.yml
name: PR prsk cheering

on:
  pull_request:
    types: [opened]

permissions:
  issues: write

jobs:
  set-prsk-label-and-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Set prsk label
        uses: narumikr/link-sekai-actions/prsk-cheering@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
