# .github/workflows/prsk-labeling.yml
name: PR prsk labeling

on:
  pull_request:
    types: [opened]

permissions:
  issues: write

jobs:
  prsk-character-labeling:
    runs-on: ubuntu-latest
    steps:
      - name: Set prsk label
        uses: narumikr/link-sekai-actions/prsk-pr-labeling@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
